name: README cards

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Base stats card
        uses: lowlighter/metrics@latest
        with:
          filename: assets/card-stats.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: eyobelakew
          template: classic
          base: header, repositories
          config_display: compact
          config_timezone: Africa/Addis_Ababa

      - name: Activity streak card
        uses: lowlighter/metrics@latest
        with:
          filename: assets/card-streak.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: eyobelakew
          template: classic
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year

      - name: Top languages card
        uses: lowlighter/metrics@latest
        with:
          filename: assets/card-langs.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: eyobelakew
          template: classic
          base: ""
          plugin_languages: yes
          plugin_languages_limit: 8
          plugin_languages_details: percentage
