name: README cards

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Stats card
        uses: lowlighter/metrics@latest
        with:
          user: eyobelakew
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.METRICS_TOKEN }}

          filename: assets/card-stats.svg
          template: classic
          config_timezone: Africa/Addis_Ababa
          config_display: compact
          config_padding: 0, 8
          config_animations: no
          base: header, repositories, metadata

      - name: Streak card
        uses: lowlighter/metrics@latest
        with:
          user: eyobelakew
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.METRICS_TOKEN }}

          filename: assets/card-streak.svg
          template: classic
          config_timezone: Africa/Addis_Ababa
          config_display: compact
          config_padding: 0, 8
          config_animations: no
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year

      - name: Top languages card
        uses: lowlighter/metrics@latest
        with:
          user: eyobelakew
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.METRICS_TOKEN }}

          filename: assets/card-langs.svg
          template: classic
          config_timezone: Africa/Addis_Ababa
          config_display: compact
          config_padding: 0, 8
          config_animations: no
          base: ""
          plugin_languages: yes
          plugin_languages_limit: 8
          plugin_languages_details: percentage
          plugin_languages_indepth: yes
          plugin_languages_analysis_timeout: 15
